from enum import Enum


class PolicyAction(Enum):

    NONE 							= "NONE"
    BOOST_FOOD 				= "BOOST_FOOD"
    BOOST_POWER 			= "BOOST_POWER"
    REDUCE_TRAFFIC 		= "REDUCE_TRAFFIC"
    DECLARE_EMERGENCY = "DECLARE_EMERGENCY"
    INCREASE_PRIORITY = "INCREASE_PRIORITY"
    LIMIT_WORKLOAD 		= "LIMIT_WORKLOAD"